UrsWorker.AssemblaTiketCreater/Controllers/AssemblaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Mvc;
using UrsWorker.Assembla.Abstractions;
using UrsWorker.Assembla.Models;
using UrsWorker.AssemblaTiketCreater.Models;

namespace UrsWorker.AssemblaTiketCreater.Controllers
{
    public class AssemblaController : Controller
    {
        private readonly IAssemblaTicketsService _assemblaTicketsService;
        private readonly IAssemblaChangesExporter _assemblaChangesExporter;
        private readonly IMilestoneProvider _milestoneProvider;
        private readonly ISpaceProvider _spaceProvider;

        public AssemblaController(
            IAssemblaTicketsService assemblaTicketsService,
            IAssemblaChangesExporter assemblaChangesExporter,
            IMilestoneProvider milestoneProvider,
            ISpaceProvider spaceProvider
        )
        {
            _assemblaTicketsService = assemblaTicketsService ?? throw new ArgumentNullException(nameof(assemblaTicketsService));
            _assemblaChangesExporter = assemblaChangesExporter ?? throw new ArgumentNullException(nameof(assemblaChangesExporter));
            _milestoneProvider = milestoneProvider ?? throw new ArgumentNullException(nameof(milestoneProvider));
            _spaceProvider = spaceProvider ?? throw new ArgumentNullException(nameof(spaceProvider));
        }

        [ResponseCache(Duration = 1800)]
        [HttpGet]
        public async Task<List<MilestoneModel>> GetMilestones(string spaceIdOrWikiNameFilter)
        {
            return await _milestoneProvider.FindAll(spaceIdOrWikiNameFilter);
        }

        [ResponseCache(Duration = 86400)]
        [HttpGet]
        public async Task<List<SpaceModel>> GetSpaces()
        {
            return await _spaceProvider.FindAll();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateTicketsProtocol([FromForm] UpdateTicketsProtocolModel updateTicketsProtocolModel)
        {
            if (string.IsNullOrEmpty(updateTicketsProtocolModel.Protocol))
            {
                return Content("Protocol does not provided");
            }

            if (string.IsNullOrEmpty(updateTicketsProtocolModel.Space))
            {
                return Content("Space not selected");
            }

            if (string.IsNullOrEmpty(updateTicketsProtocolModel.Milestone))
            {
                return Content("Milestone not selected");
            }

            await _assemblaTicketsService.UpdateProtocolAsync(
                updateTicketsProtocolModel.Protocol,
                updateTicketsProtocolModel.Space,
                updateTicketsProtocolModel.Milestone
            );


            return Ok("The tickets protocol successfully updated");
        }

        [HttpPost]
        public async Task<IActionResult> CreateTickets([FromForm] CreateTicketsModel createTicketsModel)
        {
            if (createTicketsModel.FileWithChanges == null || createTicketsModel.FileWithChanges.Length == 0)
            {
                return Content("File not selected");
            }

            if (string.IsNullOrEmpty(createTicketsModel.Space))
            {
                return Content("Space not selected");
            }

            if (string.IsNullOrEmpty(createTicketsModel.Milestone))
            {
                return Content("Milestone not selected");
            }

            using (SpreadsheetDocument spreadsheetDocument =
                SpreadsheetDocument.Open(createTicketsModel.FileWithChanges.OpenReadStream(), false))
            {
                WorkbookPart workbookPart = spreadsheetDocument.WorkbookPart;
                WorksheetPart worksheetPart = workbookPart.WorksheetParts.First();
                SheetData sheetData = worksheetPart.Worksheet.Elements<SheetData>().First();

                var allRows = sheetData.Elements<Row>().ToList();
                Row firstRow = allRows[0];

                string protocol = string.Empty;
                var firstRowCells = firstRow.Elements<Cell>().ToList();
                if (GetCellValue(spreadsheetDocument, firstRowCells[0]) == "Protocol")
                {
                    protocol = GetCellValue(spreadsheetDocument, firstRowCells[1]);
                    allRows.Remove(firstRow);
                }

                //if (string.IsNullOrEmpty(protocol))
                //{
                //    throw new Exception("Protocol is not defined");
                //}

                List<AssemblaChange> changes = new List<AssemblaChange>();
                string ticketTitle;
                string ticketDescription;
                foreach (Row row in allRows)
                {
                    var rowCells = row.Elements<Cell>().ToList();
                    if (rowCells.Count == 0)
                    {
                        continue;
                    }

                    ticketTitle = GetCellValue(spreadsheetDocument, rowCells[0]);
                    if (string.IsNullOrEmpty(ticketTitle))
                    {
                        continue;
                    }
                    ticketDescription = (rowCells.Count >= 2) ? GetCellValue(spreadsheetDocument, rowCells[1]) : string.Empty;
                    changes.Add(new AssemblaChange()
                    {
                        Description = ticketDescription,
                        Title = ticketTitle,
                        Protocol = protocol
                    });
                }

                await _assemblaChangesExporter.UploadAsync(changes.Select(x => new AssemblaChange
                {
                    Title = x.Title,
                    Description = x.Description,
                    Protocol = x.Protocol
                }), createTicketsModel.Space, createTicketsModel.Milestone);

                return Ok("The tickets successfully created");
            }
        }

        private static string GetCellValue(SpreadsheetDocument document, Cell cell)
        {
            if (cell.CellValue == null)
            {
                return null;
            }

            SharedStringTablePart stringTablePart = document.WorkbookPart.SharedStringTablePart;
            string value = cell.CellValue.InnerXml;

            if (cell.DataType != null && cell.DataType.Value == CellValues.SharedString)
            {
                return stringTablePart.SharedStringTable.ChildElements[Int32.Parse(value)].InnerText;
            }
            else
            {
                return value;
            }
        }
    }
}

UrsWorker.AssemblaTiketCreater/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UrsWorker.AssemblaTiketCreater.Models;
using UrsWorker.Parser.Abstractions;
using UrsWorker.UrsModel;
using UrsWorker.Parser.Extensions;
using UrsWorker.Parser.Models;
using Microsoft.AspNetCore.Http;

namespace UrsWorker.AssemblaTiketCreater.Controllers
{
    public class HomeController : Controller
    {
        private readonly MainOptions _options;
        private readonly IUrsModelProvider _ursParser;
        private readonly IUrsModificationProvider _changesProvider;
        private readonly IUrsModificationsExporter _changesExporter;


        public HomeController(
            IUrsModelProvider ursParser,
            IUrsModificationProvider changesProvider,
            IUrsModificationsExporter changesExporter
        )
        {
            _ursParser = ursParser ?? throw new ArgumentNullException(nameof(ursParser));
            _changesProvider = changesProvider ?? throw new ArgumentNullException(nameof(changesProvider));
            _changesExporter = changesExporter ?? throw new ArgumentNullException(nameof(changesExporter));
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TicketsProcessing()
        {
            return View();
        }

        [DisableRequestSizeLimit]
        [HttpPost]
        public async Task<IActionResult> UploadUrsAndDownloadChanges(IFormFile file)
        {
            if(file == null || file.Length == 0) {
                return Content("File not selected");
            }

            var resultStream = new MemoryStream();

            // process uploaded files
            IUrsModel ursModel = await _ursParser.GetAsync(file.OpenReadStream());
            List<UrsModification> changes =  _changesProvider.GetModifications(ursModel, true, true);

            await _changesExporter.ExportAsync(resultStream, changes);
            resultStream.Position = 0;

            string ursName = file.FileName.Replace(".docx", "");
            return File(resultStream, "application/octet-stream", $"{ursName}Changes_{DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")}.xlsx" );
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UrsWorker.AssemblaTiketCreater/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "URS parsing and ticket creating";
}

<div class="row">
    <div>
        <h1>Step 1</h1>

        <form method="post" enctype="multipart/form-data" asp-controller="Home" asp-action="UploadUrsAndDownloadChanges">
            <div class="form-group">
                <div>
                    <p>Select the URS please:</p>
                    <input type="file" name="file" />
                </div>
            </div>
            <div class="form-group">
                <div>
                    Click on "Download changes" to Upload the URS and Download the file of changes.
                    <input type="submit" value="Download changes" />
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div>
        <h1>Step 2</h1>
        <p>Check and update the dowloaded file with changes from step 1.</p>
    </div>
</div>


<div class="row">
    <div>
        <h1>Step 3</h1>

        <form id="createTicketsForm" method="post" enctype="multipart/form-data" asp-controller="Assembla" asp-action="CreateTickets">
            <div class="form-group">
                <div>
                    <p>Select the downloaded file of changes from step 2:</p>
                    <input type="file" name="fileWithChanges" id="fileWithChanges" />
                </div>
            </div>
            <div class="form-group">
                <div>
                    <p>Select a space:</p>
                    <select id="space" name="space"></select>
                </div>
            </div>
            <div class="form-group">
                <div>
                    <p>Select a milestone:</p>
                    filter:<input type="text" id="milestoneFilter" />
                    <select id="milestone" name="milestone"></select>
                </div>
            </div>
            <div class="form-group">
                <div>
                    <input type="submit" value="Create Tickets in assembla" />
                </div>
            </div>
        </form>

        @section Scripts {
            <script type="text/javascript">
                $(document).ready(function () {

                    var $space = $("#space");
                    var $milestone = $("#milestone");
                    var $milestoneFilter = $("#milestoneFilter");
                    var allMilestones = [];

                    $space.change(function () {
                        $milestone.html("");
                        $.getJSON(
                            "@Url.Action("GetMilestones", "Assembla")",
                            { spaceIdOrWikiNameFilter: $space.val() },
                            function (data) {
                                allMilestones = data;
                                $milestoneFilter.trigger("change");
                            });
                    });

                    function generateMilestonesList(milestones) {
                        var options = "";
                        $.each(milestones, function (index, item) {
                            options += "<option value='" + item.id + "'>" + item.name + "</option>"
                        });
                        $milestone.html(options);
                    }

                    $.getJSON(
                        "@Url.Action("GetSpaces", "Assembla")",
                        {},
                        function (data) {
                            var options = "";
                            $.each(data, function (index, item) {
                                options += "<option value='" + item.id + "'>" + item.name + "</option>"
                            });
                            $space.html(options);
                            if (data.length > 0) {
                                $space.val(data[0].id);
                            }
                            $space.trigger("change");
                        });

                    $milestoneFilter.on("keyup input change", function () {
                        var filter = $(this).val().toLowerCase();
                        var milestones = allMilestones.filter(function (milestone) {
                            return milestone.name.toLowerCase().indexOf(filter) >= 0;
                        });
                        generateMilestonesList(milestones);
                    });

                    $("#createTicketsForm").on("submit", function (event) {
                        event.preventDefault();
                        var file = $("#fileWithChanges")[0].files[0];
                        if (file) {
                            var formData = new FormData();
                            formData.append("fileWithChanges", file);
                            formData.append("space", $space.val());
                            formData.append("milestone", $milestone.val());

                            $.ajax({
                                url: "@Url.Action("CreateTickets", "Assembla")",
                                data: formData,
                                processData: false,
                                contentType: false,
                                type: "POST",
                                success: function (data) {
                                    alert(data);
                                },
                                error: function (data) {
                                    alert(data);
                                }
                            });
                        }
                        else {
                            alert("File not selected");
                        }
                    });
                });
            </script>
        }
    </div>
</div>

UrsWorker.AssemblaTiketCreater/Views/Home/TicketsProcessing.cshtml
@{
    ViewData["Title"] = "Tickets processing";
}

<div class="row">
    <div>
        <h1>Update protocol for all tickets from milestone</h1>

        <form id="updateTicketsProtocolForm" method="post" enctype="multipart/form-data" asp-controller="Assembla" asp-action="UpdateTicketsProtocol">
            <div class="form-group">
                <div>
                    <p>Select a space:</p>
                    <select id="space" name="space"></select>
                </div>
            </div>
            <div class="form-group">
                <div>
                    <p>Select a milestone:</p>
                    filter:<input type="text" id="milestoneFilter" />
                    <select id="milestone" name="milestone"></select>
                </div>
            </div>
            <div class="form-group">
                <div>
                    <p>Protocol:</p>
                    <input type="text" id="protocol" name="protocol" />
                </div>
            </div>
            <div class="form-group">
                <div>
                    <input type="submit" value="Update protocol" />
                </div>
            </div>
        </form>

        @section Scripts {
        <script type="text/javascript">
                $(document).ready(function () {

                    var $space = $("#space");
                    var $milestone = $("#milestone");
                    var $milestoneFilter = $("#milestoneFilter");
                    var allMilestones = [];

                    $space.change(function () {
                        $milestone.html("");
                        $.getJSON(
                            "@Url.Action("GetMilestones", "Assembla")",
                            { spaceIdOrWikiNameFilter: $space.val() },
                            function (data) {
                                allMilestones = data;
                                $milestoneFilter.trigger("change");
                            });
                    });

                    function generateMilestonesList(milestones) {
                        var options = "";
                        $.each(milestones, function (index, item) {
                            options += "<option value='" + item.id + "'>" + item.name + "</option>"
                        });
                        $milestone.html(options);
                    }

                    $.getJSON(
                        "@Url.Action("GetSpaces", "Assembla")",
                        {},
                        function (data) {
                            var options = "";
                            $.each(data, function (index, item) {
                                options += "<option value='" + item.id + "'>" + item.name + "</option>"
                            });
                            $space.html(options);
                            if (data.length > 0) {
                                $space.val(data[0].id);
                            }
                            $space.trigger("change");
                        });

                    $milestoneFilter.on("keyup input change", function () {
                        var filter = $(this).val().toLowerCase();
                        var milestones = allMilestones.filter(function (milestone) {
                            return milestone.name.toLowerCase().indexOf(filter) >= 0;
                        });
                        generateMilestonesList(milestones);
                    });

                    $("#updateTicketsProtocolForm").on("submit", function (event) {
                        event.preventDefault();
                        var protocol = $("#protocol").val();
                        if (protocol !== null && protocol !== "" && typeof protocol !== "undefined") {
                            var formData = new FormData();
                            formData.append("protocol", protocol);
                            formData.append("space", $space.val());
                            formData.append("milestone", $milestone.val());

                            $.ajax({
                                url: "@Url.Action("UpdateTicketsProtocol", "Assembla")",
                                data: formData,
                                processData: false,
                                contentType: false,
                                type: "POST",
                                success: function (data) {
                                    alert(data);
                                },
                                error: function (data) {
                                    alert(data);
                                }
                            });
                        }
                        else {
                            alert("Protocol should be provided");
                        }
                    });
                });
        </script>
        }
    </div>
</div>